version: '3.4'
services:
  phpldapadmin:
    image: kalaksi/phpldapadmin
    restart: unless-stopped
    cap_drop:
      - ALL
    volumes:
      - phpldapadmin_htdocs:/usr/share/phpldapadmin/htdocs
      - phpldapadmin_config:/etc/phpldapadmin
      - phpldapadmin_nginx_config:/etc/nginx/conf.d
  http-server:
    image: nginx:stable
    restart: unless-stopped
    depends_on:
      - phpldapadmin
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    volumes:
      - phpldapadmin_nginx_config:/etc/nginx/conf.d:ro
      - phpldapadmin_htdocs:/usr/share/phpldapadmin/htdocs:ro
    ports:
      - 80:8080/tcp
      # You need to set up HTTPS yourself if necessary.
      # Basically you need to generate the cert, move it to the config dir and edit the nginx configuration.
      # Remember to change `http` to `https` in the healthcheck, too.
      # - 443:8443/tcp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5m
      timeout: 10s
      retries: 1
      start_period: 10s

volumes:
  # Feel free to use other mechanisms for sharing configuration between containers if available.
  phpldapadmin_nginx_config: {}
  phpldapadmin_config: {}
  phpldapadmin_htdocs: {}
