version: 2
services:
  phpldapadmin:
    image: kalaksi/phpldapadmin
    container_name: phpldapadmin
    volumes:
      - phpldapadmin_htdocs:/usr/share/phpldapadmin/htdocs
      - phpldapadmin_config:/etc/phpldapadmin
      - phpldapadmin_nginx_config:/etc/nginx/conf.d

  nginx:
    image: nginx:stable
    container_name: phpldapadmin-frontend
    volumes:
      - phpldapadmin_nginx_config:/etc/nginx/conf.d:ro
      - phpldapadmin_htdocs:/usr/share/phpldapadmin/htdocs:ro
    ports:
      - 80:80/tcp
      # You need to set up HTTPS yourself if necessary.
      # - 443:443/tcp

volumes:
  # Feel free to use other mechanisms for sharing configuration between containers if available.
  phpldapadmin_nginx_config: {}
  phpldapadmin_config: {}
  phpldapadmin_htdocs: {}
